function XSPlotSulfur(Parent1, X1, YMatrix1)
%Example: XSPlotSulfur(figure,SI{:,1},SI{:,2:18})
%  PARENT1:  axes parent
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Jan-2018 13:59:41

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(loglog1(1),'DisplayName','S','Color',[1 0 0]);
set(loglog1(2),'DisplayName','S^{+}','Color',[1 0.600000023841858 0]);
set(loglog1(3),'DisplayName','S^{2+}',...
    'Color',[0.800000011920929 0.800000011920929 0]);
set(loglog1(4),'DisplayName','S^{3+}','Color',[0 1 0]);
set(loglog1(5),'DisplayName','S^{4+}','Color',[0 0 1]);
set(loglog1(6),'DisplayName','S^{5+}','Color',[0.600000023841858 0 1]);
set(loglog1(7),'DisplayName','S^{6+}',...
    'Color',[0.600000023841858 0 0.600000023841858]);
set(loglog1(8),'DisplayName','S^{7+}','Color',[0 0 0]);
set(loglog1(9),'DisplayName','S^{8+}','Color',[0 1 1]);
set(loglog1(10),'DisplayName','S^{9+}','Color',[1 0 0],'LineStyle','--');
set(loglog1(11),'DisplayName','S^{10+}','Color',[1 0.600000023841858 0],...
    'LineStyle','--');
set(loglog1(12),'DisplayName','S^{11+}',...
    'Color',[0.800000011920929 0.800000011920929 0],'LineStyle','--');
set(loglog1(13),'DisplayName','S^{12+}','Color',[0 1 0],'LineStyle','--');
set(loglog1(14),'DisplayName','S^{13+}','Color',[0 0 1],'LineStyle','--');
set(loglog1(15),'DisplayName','S^{14+}','Color',[0.600000023841858 0 1],...
    'LineStyle','--');
set(loglog1(16),'DisplayName','S^{15+}',...
    'Color',[0.600000023841858 0 0.600000023841858],'LineStyle','--');
set(loglog1(17),'DisplayName','S^{16+}','Color',[0 0 0],'LineStyle','--');

% Create ylabel
ylabel('Cross-Section [cm^{-2}]','FontWeight','bold');

% Create xlabel
xlabel('Energy [keV/u]','FontWeight','bold');

% Create title
title('Insert Process Here');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','TickDir','both','XMinorTick',...
    'on','XScale','log','YMinorTick','on','YScale','log');
